use Sol;
db.dropDatabase();

db.planets.insertMany([
    {
        name: "Mercury",
        position_from_sun: 1,
        latin_name: "Mercurius",
        sumerian_name: "Enki",
        orbit_distance_km: 57909227,
        orbit_distance_au: 0.387,
        equatorial_diameter_km: 4879,
        mass: "3.29 × 10^23 kg (0.06 Earths)",
        number_of_moons: 0,
        moon_names: {
            first: null,
        },
        rings: 0,
        orbit_period_days: 88,
        surface_temperature_max_celcius: 427,
        surface_temperature_min_celcius: -173,
        facts: {
            first: "Mercury has been known to humanity since ancient times and although its discovery date is unknown, the first mentions of the planet are believed to be around 3000 BC by the Sumerians.",
            second: "A year in Mercury is 88 days, yet a Mercury day is 176 Earth days.Mercury is nearly tidally locked to the Sun – also known as a gravitational lock – and over time this has slowed the rotation of the planet to almost match its orbit around the Sun.",
            third: "Mercury orbits so quickly around the Sun that early civilizations believed it was actually two different stars – one which appeared in the morning and another which appeared in the evening.",
            fourth: "Mercury is the smallest planet in the solar system with a diameter of 4, 879 km and is one of five planets that is visible to the naked eye.",
            fifth: "After the Earth, Mercury is the second densest planet.Despite its small size, Mercury is very dense because it is composed mainly of heavy metals and rock – the main characteristic of terrestrial planets.",
            sixth: "Mercury is named after the messenger of the Roman gods, who is also known as Hermes in Greek mythology.This is because of the speed in which Mercury orbits the Sun and the speed with which Mercury the Roman deity was able to deliver messages.",
            seventh: "Astronomers didn’t realize that Mercury was a planet until 1543 when Copernicus published his Sun- centered model of the Solar System – putting the Sun as the centre of the solar system rather than the previously believed centre, the Earth.",
            eighth: "The planet has just 38% of the gravity on Earth.This means that Mercury isn’t able to hold the atmosphere it has and it instead gets blown away by solar winds.However those same solar winds are also bringing in new gases, radioactive decay and dust from micrometeorites – replenishing the atmosphere.",
            ninth: "Mercury has no moons or rings because of its low gravity and lack of atmosphere.",
            tenth: "It was once believed that a planet called Vulcan existed between the orbit of Mercury and the Sun – however the existence of such a planet was never found.",
            eleventh: "The orbit of Mercury is an ellipse rather than circular.It has the most eccentric orbit in the solar system and the least circular of all of the planets, according to scientists and astronomers.",
            twelfth: "Mercury is only the second hottest planet.Venus, though farther from the Sun than Mercury, actually experiences higher temperatures.This is because Mercury has no atmosphere to regulate temperature and results in the most extreme temperature change of all the planets – ranging from - 170°C(-280°F) during the night to 430°C(800°F) during the day.",
            thirteenth: "Mercury does not experience any seasons.The axis of Mercury has the smallest tilt of all other planets, and this results in a lack of seasons on its surface.",
            fourteenth: "Mercury is the only planet which doesn’t rotate exactly once every year – instead rotating three times for every two orbits of the Sun.This is because it is nearly tidally locked to the Sun.",
            fifteenth: "The orbit of Mercury was important in proving Albert Einstein’s theory of General Relativity.",

        },
    },

    {
        name: "Venus",
        position_from_sun: 2,
        latin_name: "Venus",
        sumerian_name: "Inanna",
        orbit_distance_km: 108209475,
        orbit_distance_au: 0.732,
        equatorial_diameter_km: 12104,
        mass: "4.87 × 10^24 kg (0.82 Earths)",
        number_of_moons: 0,
        moon_names: {
            first: null,
        },
        rings: 0,
        orbit_distance_km: 108209475,
        orbit_distance_au: 0.73,
        orbit_period_days: 225,
        surface_temperature_max_celcius: 462,
        surface_temperature_min_celcius: 462,
        facts: {
            first: "Venus is the second brightest natural object in the sky. The planet has an apparent magnitude of -3.8 to -4.6, which makes it visible on a bright, clear day. The Moon is the only other natural object that is brighter.",
            second: "Venus is sometimes referred to as the “morning star” and “evening star”.This dates back to ancient civilizations who believed that Venus was in fact two distinct stars appearing in the sky.When the orbit of Venus overtakes Earth’s orbit, it changes from being visible at sunrise to being visible at sunset.They were known as Phosphorus and Hesperus by the Greeks, and Lucifer and Vesper by the Romans.",
            third: "One day on Venus is longer than one year. Due to the slow rotation on its axis, it takes 243 Earth-days to complete one rotation. The orbit of the planet takes 225 Earth-days – making a year on Venus shorter on day on Venus.",
            fifth: "Venus is named after the Roman goddess of love and beauty. This may be, in part, due the brightness of the planet and may date back to the Babylonians in 1581 who referred to Venus as 'bright queen of the sky'.",
            sixth: "Venus is sometimes called Earth’s sister planet. This is because their size is very similar (there is only a 638 km different in diameter) and Venus has around 81% of Earth’s mass. They are also similarly located with Venus being the closest planet to Earth. Both planets also have a central core, a molten mantle and a crust.",
            seventh: "Venus has no moons nor rings.",
            eighth: "Billions of years ago, the climate of Venus may been similar to that of Earth and scientists believe that Venus once possessed large amounts of water or oceans. However, due to the high temperatures produce from the extreme greenhouse effect, this water boiled off long ago and the surface of the planet is now too hot and hostile to sustain life.",
            ninth: "Venus rotate in the opposite direction to other planets. Most other planets rotate counter-clockwise on their axis, however Venus, like Uranus, rotates clockwise. This is known as a retrograde rotation and may have been caused by a collision with an asteroid or other object which caused the planet to change its rotational path.",
            tenth: "Venus is the hottest planet in the solar system with an average surface temperature of 462°C (863°F). Also, Venus doesn’t tilt on its axis which means there are no seasons either. The atmosphere is a dense 96.5% carbon dioxide which traps heat and caused the greenhouse effect which evaporated any water sources billions of years ago.",
            eleventh: "The temperature on Venus doesn’t vary much between the night and day. This is due to the slow movement of the solar winds across the surface of the planet.",
            twelfth: "The estimated age of the Venusian surface is around 300-400 million years old. By comparison, the surface of the Earth is about 100 million years old.",
            thirteenth: "The atmospheric pressure of Venus is 92 times stronger than Earth’s. This means that any small asteroids entering the atmosphere of Venus are crushed by the immense pressure, which is why there are no small surface craters on the planet. This pressure is equivalent to being around 1,000 km under Earth’s oceans.",
            fourteenth: "Venus has a very weak magnetic field. This surprised scientists, who expected Venus to have a magnetic field similar in strength to Earth’s. One possible reason for this is that Venus has no solid inner core, or that its core is not cooling.",
            fifteenth: "Venus is the only planet in the Solar System to be named after a female figure.",

        },
    },

    {
        name: "Earth",
        position_from_sun: 3,
        latin_name: "Terra",
        sumerian_name: "Ki",
        orbit_distance_km: 149598262,
        orbit_distance_au: 1,
        equatorial_diameter_km: 12756,
        mass: "5.97 × 10^ 24 kg",
        number_of_moons: 1,
        moon_names: {
            first: "Luna",
        },
        rings: 0,
        orbit_period_days: 365.24,
        surface_temperature_max_celcius: 58,
        surface_temperature_min_celcius: -88,
        facts: {
            first: "The Earth was once believed to be the centre of the universe. For 2000 years ancient astronomers believed that the Earth was static and had other celestial bodies travelling in circular orbits around it. They believed this because of the apparent movement on the Sun and planets in relation to their viewpoint. In 1543, Copernicus published his Sun-centered model of the Solar System which put the Sun at the centre of our solar system.",
            second: "Earth is the only planet not named for a mythological god or goddess. The other seven planets in the solar system were named after Roman gods or goddesses. For the five visible to the naked eye, Mercury, Venus, Mars, Jupiter and Saturn they we named during ancient times. This Roman method was also used after the discovery of Uranus and Neptune. The word “Earth” comes from the Old English word “ertha” meaning ground or land.",
            third: "Earth is the most dense planet in the solar system. The density of Earth differs in each part of the planet – the core, for example, is denser than the Earth’s crust – but the average density of the planet is around 5.52 grams per cubic centimetre.",
            fourth: "The gravity between the Earth and the Moon causes the tides on Earth. This effect on the Moon means it is tidally locked to Earth – its rotation period is the same as its orbit time so it always presents the same face to Earth.",
            fifth: "The rotation of the Earth is gradually slowing down. The deceleration of the Earth’s rotation is very slow, approximately 17 milliseconds per hundred years. Eventually this will lengthen our days but it will take around 140 million years before our day will have increased from 24 to 25 hours.",
            sixth: "Earth’s atmosphere is composed of 78% nitrogen, 21% oxygen, and trace amounts of other gases including argon and carbon dixoide.",
            seventh: "The large amount of oxygen on Earth comes from our plant life’s consumption of carbon dioxide during photosynthesis",
            eighth: "Earth has a very powerful magnetic field. This field protects the planet from the effects of solar winds and is believed to be a result of the nickel-iron core of the planet combined with its rapid rotation.",
            ninth: "The Earth has an Ozone Layer which protects it from harmful solar radiation. This shell is a special type of oxygen that absorbs most of the Sun’s powerful UV rays.",
            tenth: "70% of the Earth’s surface is covered by water – the remainder consists of continents and islands which together have many lakes and other sources of water.",
            eleventh: "The first life on Earth developed in the oceans through a process called abiogenesis or biopoiesis. This is a natural process in which life grows from non-living matter like simple organic compounds.",
            twelfth: "Earth’s water was initially trapped within the planet. Over time the Earth’s water was brought to the surface by the planet’s volcanic activity.",
            thirteenth: "Earth has relatively few visible impact craters compared with other solid bodies in our solar system. This is because Earth is geologically active and has processes like tectonics and erosion that reshape its surface.",
            fourteenth: "The highest point found on Earth is Mount Everest which reaches a height of 8.8 km.",
            fifteenth: "The lowest point on Earth is called Challenger Deep and at 10.9 km below sea level, it is further than the peak of Mount Everest.",

        },
    },

    {
        name: "Mars",
        position_from_sun: 4,
        latin_name: "Mars",
        sumerian_name: "Gugulanna",
        orbit_distance_km: 227943824,
        orbit_distance_au: 1.38,
        equatorial_diameter_km: 6792,
        mass: "6.39 × 10^23 kg (0.11 Earths)",
        number_of_moons: 2,
        moon_names: {
            first: "Phobos",
            second: "Deimos",
        },
        rings: 0,
        orbit_period_days: 686.98,
        surface_temperature_max_celcius: -5,
        surface_temperature_min_celcius: -87,
        facts: {
            first: "Mars and Earth have approximately the same landmass. Even though Mars has only 15% of the Earth’s volume and just over 10% of the Earth’s mass, around two thirds of the Earth’s surface is covered in water.Martian surface gravity is only 37% of the Earth’s(meaning you could leap nearly three times higher on Mars).",
            second: "Mars is home to the tallest mountain in the solar system. Olympus Mons, a shield volcano, is 21km high and 600km in diameter.Despite having formed over billions of years, evidence from volcanic lava flows is so recent many scientists believe it could still be active.",
            third: "Only 18 missions to Mars have been successful. As of September 2014 there have been 40 missions to Mars, including orbiters, landers and rovers but not counting flybys.The most recent arrivals include the Mars Curiosity mission in 2012, the MAVEN mission, which arrived on September 22, 2014, followed by the Indian Space Research Organization’s MOM Mangalyaan orbiter, which arrived on September 24, 2014. The next missions to arrive will be the European Space Agency’s ExoMars mission, comprising an orbiter, lander, and a rover, followed by NASA’s InSight robotic lander mission, slated for launch in March 2016 and a planned arrival in September, 2016.",
            fourth: "Mars has the largest dust storms in the solar system. They can last for months and cover the entire planet.The seasons are extreme because its elliptical(oval- shaped) orbital path around the Sun is more elongated than most other planets in the solar system.",
            fifth: "On Mars the Sun appears about half the size as it does on Earth. At the closest point to the Sun, the Martian southern hemisphere leans towards the Sun, causing a short, intensely hot summer, while the northern hemisphere endures a brief, cold winter: at its farthest point from the Sun, the Martian northern hemisphere leans towards the Sun, causing a long, mild summer, while the southern hemisphere endures a lengthy, cold winter.",
            sixth: "Pieces of Mars have fallen to Earth. Scientists have found tiny traces of Martian atmosphere within meteorites violently ejected from Mars, then orbiting the solar system amongst galactic debris for millions of years, before crash landing on Earth.This allowed scientists to begin studying Mars prior to launching space missions.",
            seventh: "Mars takes its name from the Roman god of war. The ancient Greeks called the planet Ares, after their god of war; the Romans then did likewise, associating the planet’s blood- red colour with Mars, their own god of war.Interestingly, other ancient cultures also focused on colour – to China’s astronomers it was ‘the fire star’, whilst Egyptian priests called on ‘Her Desher’, or ‘the red one’.The red colour Mars is known for is due to the rock and dust covering its surface being rich in iron.",
            eighth: "There are signs of liquid water on Mars. For years Mars has been known to have water in the form of ice.The first signs of trickling water are dark stripes or stains on crater wall and cliffs seen in satellite images.Due to Mars’ atmosphere this water would have to be salty to prevent it from freezing or vaporising.",
            ninth: "One day Mars will have a ring. In the next 20-40 million years Mars’ largest moon Phobos will be torn apart by gravitational forces leading to the creation of a ring that could last up to 100 million years.",
            tenth: "Sunsets on Mars are blue. During the martian day the sky is pinkish- red, this is the opposite of the Earth’s skies.",
            eleventh: "It's thought that Mars's core is predominantly made up of iron, but also nickel and sulphur. The core is about half the size of the planet and may be entirely liquid, or have a solid iron centre and a liquid exterior.",
            twelfth: "The deepest canyon on the planet is Valles Marineris at 7 kilometres - Earth's Grand Canyon is only 1.8 kilometres deep. Valles Marineris was mostly formed by tectonic processes.",
            thirteenth: "Mars's thin atmosphere makes for extreme temperature differences on the planet. When the Sun's energy enters the atmosphere, it is not equally dispersed and easily escapes back out into space.",
            fourteenth: "Mars has an elliptical orbit, meaning it is egg- or oval-shaped. This means that throughout its year, Mars's distance from the Sun ranges between around 206 million and 249 million kilometres. ",
            fifteenth: "Mars has a large, dark patch on its surface, known as the Syrtis Major Planum. It reaches around 1,500 kilometres north from the equator and is around 1,000 kilometres in width. The dark colour is due to its primarily basalt rock composition.",

        },
    },

    {
        name: "Jupiter",
        position_from_sun: 5,
        latin_name: "Iuppiter",
        sumerian_name: "Enlil",
        orbit_distance_km: 778340821,
        orbit_distance_au: 5.20,
        equatorial_diameter_km: 142984,
        mass: "1.90 × 10^27 kg (318 Earths)",
        number_of_moons: 79,
        moon_names: {
            first: "Metis",
            second: "Adrastea",
            third: "Amalthea",
            fourth: "Thebe",
            fifth: "Io",
            sixth: "Europa",
            seventh: "Ganymede",
            eighth: "Callisto",
            ninth: "Themisto",
            tenth: "Leda",
            eleventh: "Ersa",
            twelfth: "Pandia",
            thirteenth: "Himalia",
            fourteenth: "Lysithea",
            fifteenth: "Elara",
            sixteen: "Dia",
            seventeen: "Carpo",
            eighteen: "Valetudo",
            nineteen: "Euporie",
            twentieth: "Eupheme",
            twenty_one: "S/2003 J 1",
            twenty_two: "S/2010 J 2",
            twenty_three: "Helike",
            twenty_four: "S/2003 J 16",
            twenty_five: "S/2003 J 2",
            twenty_six: "Euanthe",
            twenty_seven: "S/2017 J 7",
            twenty_eight: "Hermippe",
            twenty_nine: "Praxidike",
            thirtieth: "Thyone",
            thirty_one: "Thelxinoe",
            thirty_two: "S/2017 J 3",
            thirty_three: "Ananke",
            thirty_four: "Mneme",
            thirty_five: "S/2016 J 1",
            thirty_six: "Orthosie",
            thirty_seven: "Harpalyke",
            thirty_eight: "Iocaste",
            thirty_nine: "S/2017 J 9",
            fortieth: "S/2003 J 12",
            forty_one: "S/2003 J 4",
            forty_two: "Erinome",
            forty_three: "Aitne",
            forty_four: "Herse",
            forty_five: "Taygete",
            forty_six: "S/2017 J 2",
            forty_seven: "S/2017 J 6",
            forty_eight: "Eukelade",
            forty_nine: "Carme",
            fiftieth: "S/2003 J 19",
            fifty_one: "Isonoe",
            fifty_two: "S/2003 J 10",
            fifty_three: "Autonoe",
            fifty_four: "Philophrosyne",
            fifty_five: "Cyllene",
            fifty_six: "Pasithee",
            fifty_seven: "S/2010 J 1",
            fifty_eight: "Pasiphae",
            fifty_nine: "Sponde",
            sixtieth: "S/2017 J 8",
            sixty_one: "Eurydome",
            sixty_two: "S/2017 J 5",
            sixty_three: "Kalyke",
            sixty_four: "Hegemone",
            sixty_five: "Kale",
            sixty_six: "Kallichore",
            sixty_seven: "S/2011 J 1",
            sixty_eight: "S/2017 J 1",
            sixty_nine: "Chaldene",
            seventieth: "Arche",
            seventy_one: "Eirene",
            seventy_two: "Kore",
            seventy_three: "S/2011 J 2",
            seventy_four: "S/2003 J 9",
            seventy_five: "Megaclite",
            seventy_six: "Aoede",
            seventy_seven: "S/2003 J 23",
            seventy_eight: "Callirrhoe",
            seventy_nine: "Sinope",
        },
        rings: 4,
        orbit_period_days: 4333,
        surface_temperature_max_celcius: -108,
        surface_temperature_min_celcius: -161,
        facts: {
            first: "Jupiter is the fourth brightest object in the solar system. Only the Sun, Moon and Venus are brighter.It is one of five planets visible to the naked eye from Earth.",
            second: "The ancient Babylonians were the first to record their sightings of Jupiter. This was around the 7th or 8th century BC.Jupiter is named after the king of the Roman gods.To the Greeks, it represented Zeus, the god of thunder.The Mesopotamians saw Jupiter as the god Marduk and patron of the city of Babylon.Germanic tribes saw this planet as Donar, or Thor.",
            third: "Jupiter has the shortest day of all the planets. It turns on its axis once every 9 hours and 55 minutes.The rapid rotation flattens the planet slightly, giving it an oblate shape.",
            fourth: "Jupiter orbits the Sun once every 11.8 Earth years. From our point of view on Earth, it appears to move slowly in the sky, taking months to move from one constellation to another.",
            fifth: "Jupiter has unique cloud features. The upper atmosphere of Jupiter is divided into cloud belts and zones.They are made primarily of ammonia crystals, sulfur, and mixtures of the two compounds.",
            sixth: "The Great Red Spot is a huge storm on Jupiter. It has raged for at least 350 years.It is so large that three Earths could fit inside it.",
            seventh: "Jupiter’s interior is made of rock, metal, and hydrogen compounds. Below Jupiter’s massive atmosphere(which is made primarily of hydrogen), there are layers of compressed hydrogen gas, liquid metallic hydrogen, and a core of ice, rock, and metals.",
            eighth: "Jupiter’s moon Ganymede is the largest moon in the solar system. Jupiter’s moons are sometimes called the Jovian satellites, the largest of these are Ganymeade, Callisto Io and Europa. Ganymeade measures 5, 268 km across, making it larger than the planet Mercury.",
            ninth: "Jupiter has a thin ring system. Its rings are composed mainly of dust particles ejected from some of Jupiter’s smaller worlds during impacts from incoming comets and asteroids.The ring system begins some 92, 000 kilometres above Jupiter’s cloud tops and stretches out to more than 225, 000 km from the planet.They are between 2, 000 to 12, 500 kilometres thick.",
            tenth: "Eight spacecraft have visited Jupiter. Pioneer 10 and 11, Voyager 1 and 2, Galileo, Cassini, Ulysses, and New Horizons missions.The Juno mission is its way to Jupiter and will arrive in July 2016. Other future missions may focus on the Jovian moons Europa, Ganymede, and Callisto, and their subsurface oceans.",
            eleventh: "Jupiter is sometimes considered a failed star. If Jupiter had become 80 times more massive, nuclear fusion would have occurred in its core. Had that happened, it would have become a star instead of a planet.",
            twelfth: "Jupiter does not experience seasons like other planets such as Earth and Mars. This is because the axis is only tilted by 3.13 degrees.",
            thirteenth: "Jupiter is the only planet that has a center of mass with the Sun that lies outside the volume of the Sun, though by only 7% of the Sun’s radius.",
            fourteenth: "The largest of Jupiter’s moons, Ganymede is the largest moon in the solar system. The moons are sometimes called the Jovian satellites and the largest of them are Ganymede, Callisto, Io and Europa. Ganymede is larger than the planet Mercury with a diameter of around 5,268 km.",
            fifteenth: "Jupiter actually experiences the most intense auroras in the solar system, being hundreds of times brighter than on Earth. Just like on Earth, auroras on Jupiter are caused by solar storms. However, Jupiter has an additional source for its auroras: charged particles thrown into space by its orbiting moon Io, which is famous for its many large volcanoes.",

        },
    },

    {
        name: "Saturn",
        position_from_sun: 6,
        latin_name: "Saturnus",
        sumerian_name: "Ninurta",
        orbit_distance_km: 1426666422,
        orbit_distance_au: 9.58,
        equatorial_diameter_km: 120536,
        mass: "5.68 × 10^26 kg (95 Earths)",
        number_of_moons: 82,
        moon_names: {
            first: "S/2009 S 1",
            second: "Pan",
            third: "Daphnis",
            fourth: "Atlas",
            fifth: "Prometheus",
            sixth: "Pandora",
            seventh: "Epimetheus",
            eighth: "Janus",
            ninth: "Aegaeon",
            tenth: "Mimas",
            eleventh: "Methone",
            twelfth: "Anthe",
            thirteenth: "Pallene",
            fourteenth: "Enceladus",
            fifteenth: "Tethys",
            sixteen: "Telesto",
            seventeen: "Calypso",
            eighteen: "Dione",
            nineteen: "Helene",
            twentieth: "Polydeuces",
            twenty_one: "Rhea",
            twenty_two: "Titan",
            twenty_three: "Hyperion",
            twenty_four: "Iapetus",
            twenty_five: "Kiviuq",
            twenty_six: "Ijiraq",
            twenty_seven: "Phoebe",
            twenty_eight: "Paaliaq",
            twenty_nine: "Skathi",
            thirtieth: "S/2004 S 37",
            thirty_one: "S/2007 S 2",
            thirty_two: "Albiorix",
            thirty_three: "Bebhionn",
            thirty_four: "S/2004 S 29",
            thirty_five: "Skoll",
            thirty_six: "S/2004 S 31",
            thirty_seven: "Erriapus",
            thirty_eight: "Tarqeq",
            thirty_nine: "Siarnaq",
            fortieth: "Tarvos",
            forty_one: "Hyrrokkin",
            forty_two: "Greip",
            forty_three: "Mundilfari",
            forty_four: "S/2004 S 13",
            forty_five: "S/2006 S 1",
            forty_six: "S/2007 S 3",
            forty_seven: "Suttungr",
            forty_eight: "S/2004 S 20",
            forty_nine: "Jarnsaxa",
            fiftieth: "Narvi",
            fifty_one: "Bergelmir",
            fifty_two: "Hati",
            fifty_three: "S/2004 S 17",
            fifty_four: "S/2004 S 12",
            fifty_five: "S/2004 S 27",
            fifty_six: "Farbauti",
            fifty_seven: "Thrymr",
            fifty_eight: "Bestla",
            fifty_nine: "S/2004 S 7",
            sixtieth: "Aegir",
            sixty_one: "S/2004 S 30",
            sixty_two: "S/2004 S 22",
            sixty_three: "S/2004 S 25",
            sixty_four: "S/2004 S 32",
            sixty_five: "S/2004 S 23",
            sixty_six: "S/2006 S 3",
            sixty_seven: "S/2004 S 35",
            sixty_eight: "Kari",
            sixty_nine: "S/2004 S 28",
            seventieth: "Loge",
            seventy_one: "S/2004 S 38",
            seventy_two: "Fenrir",
            seventy_three: "Ymir",
            seventy_four: "Surtur",
            seventy_five: "S/2004 S 33",
            seventy_six: "S/2004 S 24",
            seventy_seven: "S/2004 S 21",
            seventy_eight: "S/2004 S 39",
            seventy_nine: "S/2004 S 36",
            eightieth: "Fornjot",
            eighty_one: "S/2004 S 34",
            eighty_two: "S/2004 S 26",
        },
        rings: 7,
        orbit_period_days: 10756,
        surface_temperature_max_celcius: -122,
        surface_temperature_min_celcius: -185,
        facts: {
            first: "Saturn is the most distant planet that can be seen with the naked eye. It is the fifth brightest object in the solar system and is also easily studied through binoculars or a small telescope.",
            second: "Saturn was known to the ancients, including the Babylonians and Far Eastern observers. It is named for the Roman god Saturnus, and was known to the Greeks as Cronus.",
            third: "Saturn is the flattest planet. Its polar diameter is 90% of its equatorial diameter, this is due to its low density and fast rotation.Saturn turns on its axis once every 10 hours and 34 minutes giving it the second- shortest day of any of the solar system’s planets.",
            fourth: "Saturn orbits the Sun once every 29.4 Earth years. Its slow movement against the backdrop of stars earned it the nickname of “Lubadsagush” from the ancient Assyrians.The name means “oldest of the old”.",
            fifth: "Saturn’s upper atmosphere is divided into bands of clouds. The top layers are mostly ammonia ice.Below them, the clouds are largely water ice.Below are layers of cold hydrogen and sulfur ice mixtures.",
            sixth: "Saturn has oval-shaped storms similar to Jupiter’s. The region around its north pole has a hexagonal- shaped pattern of clouds.Scientists think this may be a wave pattern in the upper clouds.The planet also has a vortex over its south pole that resembles a hurricane- like storm.",
            seventh: "Saturn is made mostly of hydrogen. It exists in layers that get denser farther into the planet.Eventually, deep inside, the hydrogen becomes metallic.At the core lies a hot interior.",
            eighth: "Saturn has the most extensive rings in the solar system. The Saturnian rings are made mostly of chunks of ice and small amounts of carbonaceous dust.The rings stretch out more than 120, 700 km from the planet, but are amazingly thin: only about 20 meters thick.",
            ninth: "Saturn has 150 moons and smaller moonlets. All are frozen worlds.The largest moons are Titan and Rhea.Enceladus appears to have an ocean below its frozen surface.",
            tenth: "Titan is a moon with complex and dense nitrogen-rich atmosphere. It is composed mostly of water ice and rock.Its frozen surface has lakes of liquid methane and landscapes covered with frozen nitrogen.Planetary scientists consider Titan to be a possible harbour for life, but not Earth-like life",
            eleventh: "Four spacecraft have visited Saturn. Pioneer 11, Voyager 1 and 2, and the Cassini- Huygens mission have all studied the planet.Cassini orbited Saturn from July 2004 until September 2017, sending back a wealth of data about the planet, its moons, and rings.",
            twelfth: "Saturn has more moons than any other planet. 20 new moons were discovered in 2019 bring the total to 82, 3 more than Jupiter.",
            thirteenth: "Galileo Galilei was the first to see Saturn's rings in 1610, although from his telescope the rings looked more like handles or arms. Forty five years later, in 1655, Dutch astronomer Christiaan Huygens, who had a more powerful telescope, later proposed that Saturn had a thin, flat ring.",
            fourteenth: "Though scientists have identified many moons, Saturn has other small moons constantly being created and destroyed.",
            fifteenth: "As the most massive planet in the solar system after Jupiter, the pull of Saturn's gravity has helped shape the fate of our solar system. It may have helped violently hurl Neptune and Uranus outward. Along with Jupiter, it might also have slung a barrage of debris toward the inner planets early in the system's history.",

        },
    },

]);